Feature/#15 프론트엔드 테스트 코드 작성 및 절대경로 수정
woowa-techcamp-2021/store-2 pull request #22
Opened 2021-08-13 20:11 UTC by yoonminsang

## 개요 

프론트엔드 테스트 코드 작성
- 기본
- 리액트
- 리덕스

절대경로 수정

## 이슈 번호 

closes #15 

## 변경사항 

- 테스트는 내일.. 이아니라 오늘 게더에서 설명드릴게요
- Link오류는 경로 문제
- 웹팩 플러그인 설치해서 중복설정 막음
- @가 오류떠서 Root로 지정
- 바꿀수있으면 바꿔도 됩니다.

## 참고사항

- 메인에서 링크 달아놨음 각각 페이지
- css는 안했어요

## 추가 구현 필요사항

api대충 받아오는 사가 테스트 코드는 있는데 로딩하는부분은 아직 안만들었음
졸려서 그만...

## 스크린샷 
<img width="1792" alt="스크린샷 2021-08-14 오전 5 07 38" src="https://user-images.githubusercontent.com/57904979/129413153-24d48e8b-d576-45f0-964f-fd405a4e875c.png">

2021-08-13 20:26 UTC, KangyeolLee commented
언능 주무세요 민상님!!!!

2021-08-14 04:55 UTC, edegiil reviewed
절대경로만 수정하면 될 것 같습니다 양이 많네요 고생 하셨습니다!

2021-08-14 04:55 UTC, edegiil commented on .gitignore
> +__snapshots__
제일 아래 한줄 더해주세요

2021-08-14 04:55 UTC, edegiil commented on client/config/webpack.common.js
> +    plugins: [new TsconfigPathsPlugin()],
~~`tsconfig-paths`도 설치되어 있는데, 웹팩 플러그인으로 사용하면 실행할때도 `tsconfigs-paths/register`를 사용하지 않아도 되나요?~~
이건 백엔드에서 하는 거였네요.. 웹팩에 `alias`를 없애 줄수 있겠네요

2021-08-14 04:55 UTC, edegiil commented on client/src/store/test-example/ex2.ts
> +  const users = yield call(api.getUsers) as unknown as string[];
이부분은 `as`를 두번 써야하는건가요?

2021-08-14 04:55 UTC, edegiil commented on client/src/store/test-example/ex3.test.tsx
> +*/
아하 그렇군요

2021-08-14 04:55 UTC, edegiil commented on client/tsconfig.json
> +      "Root/*": ["src/*"]
여기도 백엔드 처럼 `"baseUrl": "./src", "paths": {"/*": ["/*"]},` 이렇게 하면 절대경로 잘 적용될 것 같습니다

2021-08-14 07:07 UTC, negu63 reviewed
고생하셨습니다!
세심한 예제까지ㅠㅠㅠ 감사합니다

2021-08-14 07:27 UTC, yoonminsang commented on .gitignore
> +__snapshots__
앗... 넵

2021-08-14 07:28 UTC, yoonminsang commented on client/src/store/test-example/ex2.ts
> +  const users = yield call(api.getUsers) as unknown as string[];
잘모르겠어요.. 오류뜨길래 그냥 fix했어요

2021-08-14 07:32 UTC, yoonminsang commented on client/tsconfig.json
> +      "Root/*": ["src/*"]
그렇게하면 오류가 뜹니다. 바꾸시고싶으시면 한번 테스트하고 바꾸셔도 됩니다.

2021-08-14 07:55 UTC, edegiil commented
절대경로를 수정해서 올렸습니다

2021-08-14 07:56 UTC, Seogeurim commented on client/config/webpack.common.js
> +    plugins: [new TsconfigPathsPlugin()],
웹팩에 alias를 지정하는 것과 플러그인을 지정하는 것엔 어떤 차이가 있나요?

2021-08-14 07:56 UTC, edegiil approved these changes
절대경로를 수정했습니다.

2021-08-14 07:58 UTC, edegiil commented on client/tsconfig.json
> +      "Root/*": ["src/*"]
고쳤습니다

2021-08-14 08:00 UTC, negu63 approved these changes

2021-08-14 08:04 UTC, Seogeurim reviewed
많은 테스트 생소한 테스트 혼자서 코드 짜시느라 너무 수고하셨습니다 !!! 테스트 코드 관련해서 아직 무엇이 좋고 나쁜지 숙지가 안 되어서, 조금 더 찾아보고 회의 때 민상님께 설명 듣고 다시 한 번 더 리뷰하겠습니다 !! 

한 가지 제안점은, 테스트 관련 파일들이 한 눈에 보기가 쉽지 않은데 src와 별도로 test 폴더를 만들어서 관리하는 것은 어떤가요?

2021-08-14 08:04 UTC, Seogeurim commented on client/src/store/test-example/ex2.ts
> +  const users = yield call(api.getUsers) as unknown as string[];
흠 왜 두 번 쓰는지 궁금합니다!

2021-08-14 08:04 UTC, Seogeurim commented on client/src/store/test-example/ex3.test.tsx
> +*/
오호 👀

2021-08-14 08:06 UTC, Seogeurim requested changes
린트, 주석 등!

2021-08-14 08:08 UTC, yoonminsang commented on client/tsconfig.json
> +      "Root/*": ["src/*"]
넵.. 제 git이 이상해진지알고 혼자 리벌트하고 있었네요 ㅋㅋㅋ

2021-08-14 08:08 UTC, yoonminsang commented on client/jest.config.js
> +  // ],
그 주석은 테스트코드 경로를 어디다 적을지 논의를 안해서 나중에 할려고그랬습니다
커밋에 써놨어요 ㅠㅠ

2021-08-14 08:09 UTC, yoonminsang commented on client/src/components/test-example/LoginForm.test.tsx
> +    const password = getByLabelText('비밀번호');
그거 이따 게더에서 말씀드릴려구요

2021-08-14 09:43 UTC, Seogeurim commented on client/jest.config.js
> +  // ],
ㅋㅋㅋㅋㅋㅋㅋㅋ커밋까지는 못 봤네요

2021-08-14 14:35 UTC, merged