Feature/#96 맞춤 상품 추천 API
woowa-techcamp-2021/store-2 pull request #99
Opened 2021-08-22 06:16 UTC by negu63

## 개요 

유저의 상품 열람기록을 로컬 스토리지에 저장하고 유저의 상품 열람기록에 따라 맞춤 상품을 반환하는 API를 개발하고 클라이언트와 연결했습니다
상품 추천은 AI 언어모델 [KoBERT](https://sktelecom.github.io/project/kobert/)를 이용해 생성한 상품 이름들의 코사인 유사도 비교를 통해 이루어집니다
추천에 관한 자세한 내용은 추후 위키에 정리하도록 하겠습니다

## 이슈 번호 

 - #96

## 변경사항 

- ### 클라이언트
  - 상품 클릭 시 로컬 스토리지에 열람기록 저장
  - 서버로 메인 아이템 요청 시 body에 열람기록을 전달하기 위해 get요청을 post요청으로 변경 (axios는 get 요청에 body를 담을 수 없음)
- ### 서버 
  - /api/items/main 라우터 요청받는 방식 get에서 post로 변경
  - items 서비스에서 메인 아이템을 처리하는 함수mainItems에서 req를 인자로 받도록 변경 (req.body = 상품 열람기록)
  - 상품별 유사도를 저장하고 추천에 이용하기 위해 시퀄라이즈 score 모델 추가
  - 데이터베이스에 Scores 테이블 추가 및 데이터 삽입

## 참고사항

 - 현재 메인 페이지에서는 추천 상품 12개를 받아오고 있는데 상품이 중복되거나 12개 이상이 표시되는 경우가 있습니다. 이는 추후 데이터 베이스에서 중복 상품을 제거하면 해결 될 것 같습니다
 - 상품 열람기록 뿐 아니라 상품 구매기록이나 찜에 대한 추천 상품도 가져와서 각 유사도를 비율(구매5:찜3:열람2 등)에 따라 계산하는 과정을 더 거치면 정확도를 높일 수 있을 것 같습니다

## 추가 구현 필요사항

 - 카테고리별 추천 상품 기능을 구현해야 합니다
 - 데이터베이스에서 중복 상품을 제거해야 합니다

## 스크린샷 

### 상품 열람기록
![image](https://user-images.githubusercontent.com/86910140/130344282-a77f6de8-6a0d-42c1-a621-674a95c1e739.png)

### 맞춤 추천 상품
![image](https://user-images.githubusercontent.com/86910140/130344261-01cf9be6-cf7b-4f61-8146-c45cea9b493b.png)

### 계산된 코사인 유사도
<img width="30%" src="https://user-images.githubusercontent.com/86910140/130344429-b912bd7a-f575-4b33-bb5d-13b2c6cda890.png"/>

2021-08-22 15:51 UTC, yoonminsang commented on server/src/controllers/items.ts
> +    const { popularItems, newItems, recommendItems } = await itemService.mainItems(req);
저는 컨트롤러에서 서비스로 req가 아니라 가공된 정보를 넘겨주는데 보통 이렇게 하더라구요
왜냐하면 req 자체를 서비스로 넘겨줄 필요가 없는데 req에는 많은 데이터가 담겨있습니다. 그중에 필요한 정보는 일부에요
다른분들도 댓글남겨주세요
제가 아는게많이없어서 더 많은 이유를 말하지 못하겠네요

2021-08-22 15:54 UTC, yoonminsang approved these changes
현재 메인 페이지에서는 추천 상품 12개를 받아오고 있는데 상품이 중복되거나 12개 이상이 표시되는 경우가 있습니다. 이는 추후 데이터 베이스에서 중복 상품을 제거하면 해결될 것 같습니다
라고 적어주셨는데 보니까 limit를 안적으신것같아요
시간이 된다면 말씀하신 부분도 적용하고 db도 만들어서 하면 더 좋겠네요
고생하셨습니다

2021-08-23 03:59 UTC, negu63 commented on server/src/controllers/items.ts
> +    const { popularItems, newItems, recommendItems } = await itemService.mainItems(req);
아!! 이해됐어요 req를 넘겨주는건 낭비네요 ㅎㅎ 필요한 것만 넘겨주도록 변경했습니다~

2021-08-23 03:59 UTC, negu63 commented
> 현재 메인 페이지에서는 추천 상품 12개를 받아오고 있는데 상품이 중복되거나 12개 이상이 표시되는 경우가 있습니다. 이는 추후 데이터 베이스에서 중복 상품을 제거하면 해결될 것 같습니다
> 라고 적어주셨는데 보니까 limit를 안적으신것같아요
> 시간이 된다면 말씀하신 부분도 적용하고 db도 만들어서 하면 더 좋겠네요
> 고생하셨습니다

그러네요 limit를 걸면 되겠네요 
리미트 걸고 중복 데이터 삭제하겠습니다~ 감사합니다

2021-08-23 04:18 UTC, edegiil reviewed
오오

2021-08-23 04:18 UTC, edegiil commented on client/src/components/item/index.tsx
> +          let visitedList = JSON.parse(data) as string[];
이부분은 혹시나 로컬스토리지가 공격? 받으면 에러가 바로 날것 같아서 조금 불안정한 것 같습니다. 그래서 parse를 사용하지 말고 `,`로 구분해서 문자열로 저장하고, 꺼내올때는 `split(',')`으로 분리를 하는게 어떨까요?

2021-08-23 04:18 UTC, edegiil commented on client/src/utils/api/items.ts
> +  return client.post<IMainItems>('/api/items/main', JSON.parse(visited) as string[]);
~~다른쪽 코드들은 payload로 받아와서 처리를 해주는 것 같아서 여기서도 그렇게 해주면 어떨까요?~~
saga를 통하지 않는군요

2021-08-23 04:18 UTC, edegiil commented on server/src/routes/items/index.ts
> +router.post('/main', getMainItems);
이 부분은 post로 한 이유가 있을까요?

2021-08-23 04:22 UTC, Seogeurim commented on client/src/components/item/index.tsx
> +          let visitedList = JSON.parse(data) as string[];
우와 이런 방향이 있네요 ㅎㅎ 신기합니다 ㅎㅎ

2021-08-23 04:34 UTC, Seogeurim approved these changes
AI 추천 너무 멋있네요 !!! 설명해주신 것을 듣고 더 잘 이해했습니다 ㅎㅎㅎ
너무 수고하셨습니다 ~~!!!

2021-08-23 04:34 UTC, Seogeurim commented on client/src/components/item/index.tsx
> +        if (localStorage.getItem('visited') === null) {
```suggestion
        if (!localStorage.getItem('visited')) {
```
로 조건문 줄일 수 있지 않을까용?

2021-08-23 04:34 UTC, Seogeurim commented on client/src/components/item/index.tsx
> +      onClick={(e: MouseEvent) => {
온클릭 함수 `useCallback`으로 빼면 더 좋을 것 같아요!! 저번 PR에서 화살표 함수 쓰면 렌더링될 때마다 새로 만들어진다고 했던 이유로요 !

2021-08-23 04:34 UTC, Seogeurim commented on server/src/repositories/items.ts
> +        [Op.or]: visited.reverse().slice(0, 5),
여기 reverse, slice는 어떤 처리를 해주는 부분인가요?
아 최근 5개를 뽑는 것인가요?

2021-08-23 04:34 UTC, Seogeurim commented on server/src/repositories/items.ts
> +  });
```suggestion
  rank.sort((a, b) => b.score - a.score);
```
로 줄일 수 있지 않을까요!?

2021-08-23 04:35 UTC, Seogeurim commented on server/src/routes/items/index.ts
> +router.post('/main', getMainItems);
PR 설명에 있는 것 같아요 !

2021-08-23 04:41 UTC, Seogeurim requested changes
db 변경 후 테스트 후 어푸룹 하겠습니다!!

2021-08-23 05:02 UTC, negu63 commented on client/src/components/item/index.tsx
> +          let visitedList = JSON.parse(data) as string[];
오 훨씬 좋은 방법인 것 같아요 수정했습니다!

2021-08-23 05:05 UTC, edegiil commented on server/src/routes/items/index.ts
> +router.post('/main', getMainItems);
그렇네요. 열람기록을 주는 거라면 쿠키로 주고 받으면서 GET을 사용하는 방법도 있을 것 같네요.. 물론 그렇게 하면 좀 더 많은 코드 변경이 있어야 하겠구요

2021-08-23 05:08 UTC, negu63 commented on server/src/repositories/items.ts
> +  });
와 이게 되네요 ! 수정했습니다 감사합니다~

2021-08-23 05:08 UTC, negu63 commented on client/src/components/item/index.tsx
> +        if (localStorage.getItem('visited') === null) {
그러네요 !null이 true군요 수정했습니다~

2021-08-23 05:10 UTC, negu63 commented on server/src/repositories/items.ts
> +        [Op.or]: visited.reverse().slice(0, 5),
유저 방문 기록이 로컬 스토리지에 스택형태로 저장 되어있어서
가장 최근의 5개를 뽑아 오려고 뒤집고 앞의 5개를 잘라오는 부분이에요
slice(5, 10)으로 할 수도 있겠지만
그럴 경우에 10개 이하일 경우를 커버 못 할 것 같아서
뒤집고 5개를 잘라오게 했습니다~

2021-08-23 05:11 UTC, negu63 commented on server/src/routes/items/index.ts
> +router.post('/main', getMainItems);
엑시오스 get요청에는 body를 넣을 수가 없다고 해서
로컬 스토리지에 있는 유저의 상품 열람기록을 전송하기 위해 post로 변경했어요~

2021-08-23 05:11 UTC, negu63 commented on client/src/utils/api/items.ts
> +  return client.post<IMainItems>('/api/items/main', JSON.parse(visited) as string[]);
넵 그렇습니다 ㅎㅎ

2021-08-23 05:13 UTC, Seogeurim commented on server/src/repositories/items.ts
> +        [Op.or]: visited.reverse().slice(0, 5),
오오 그렇군요 이해했습니다 !! 감사합니다 ~~!!!

2021-08-23 05:14 UTC, Seogeurim commented on client/src/components/item/index.tsx
> +      onClick={(e: MouseEvent) => {
```js
if (!localStorage.getItem('visited')) {
          localStorage.setItem('visited', title);
        } else {
          const data = localStorage.getItem('visited') as string;
          let visitedList = data.split(',');
          visitedList.push(title);
          if (visitedList.length > 10) {
            visitedList = visitedList.slice(1);
          }
          localStorage.setItem('visited', visitedList.join(','));
        }if (!localStorage.getItem('visited')) {
          localStorage.setItem('visited', title);
        } else {
          const data = localStorage.getItem('visited') as string;
          let visitedList = data.split(',');
          visitedList.push(title);
          if (visitedList.length > 10) {
            visitedList = visitedList.slice(1);
          }
          localStorage.setItem('visited', visitedList.join(','));
        }
```

이 부분을 

```js
const onItemClick = (e: MouseEvent) => {
    if ((e.target as HTMLDivElement).classList.contains('like')) return;
/* 여기 */
    onClick();
  };
```
로 옮겨도 되겠네요 !!

2021-08-23 05:15 UTC, Seogeurim approved these changes
테스트 시 잘 작동합니다 !!! 이제 머지 충돌을 해결하면 되겠네용 ㅎㅎ 😆

2021-08-23 05:16 UTC, Seogeurim commented on client/src/components/item/index.tsx
> +      onClick={(e: MouseEvent) => {
아니다 위 부분을 setVisitedItem 등의 함수로 만들고 
```js
const onItemClick = (e: MouseEvent) => {
    if ((e.target as HTMLDivElement).classList.contains('like')) return;
    setVisitedItem();
    onClick();
  };
```
이라 해도 되겠네요 !

2021-08-23 05:31 UTC, negu63 commented on client/src/components/item/index.tsx
> +      onClick={(e: MouseEvent) => {
넵! 아이템 클릭 안으로 옮겼습니다~

2021-08-23 06:55 UTC, merged